### ISSUE TITLE
ImportError: cannot import name 'Worker' on Example

### ISSUE THREAD

**Issue by javimey** [cdrx/faktory_worker_python#11]
I am trying to use the Worker Example, and I am getting the following error.

```$ python3.6 worker-example.py
Traceback (most recent call last):
  File "faktory.py", line 1, in <module>
    from faktory import Worker
  File "/home/ubuntu/scale/python-service/faktory.py", line 1, in <module>
    from faktory import Worker
ImportError: cannot import name 'Worker'```

Faktory is installed, since the Client is working perfectly fine.

I am running it in ubuntu 14.04 and I am using python 3.6.

Any ideas of what is going on? I will update the README.md if necessary after finding the issue.

**Comment by javimey** [comment]
You are my hero. I didn't see that in hours.
