### ISSUE TITLE
Cannot install version 0.5.0 via pip

### ISSUE THREAD

**Issue by joosterman** [cdrx/faktory_worker_python#34]
Today an update of Faktory was released (0.5.0) which included the `backtrace` parameter, but also the changes the following commit: https://github.com/cdrx/faktory_worker_python/commit/4aaaa37f17552729daa0feafced0492de82cb50a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

The setup.py now refers to files that do not seem to be packaged. Below the output when I run `pip install faktory==0.5.0` on MacOSX

```
Collecting faktory==0.5.0
  Downloading faktory-0.5.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/anaconda3/envs/blendle-streaming/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b7/tph8q_z12_lb13s4wd7rk1ch0000gn/T/pip-install-qkkjas4s/faktory_710524b00c484ed9950199e63eee2b3d/setup.py'"'"'; __file__='"'"'/private/var/folders/b7/tph8q_z12_lb13s4wd7rk1ch0000gn/T/pip-install-qkkjas4s/faktory_710524b00c484ed9950199e63eee2b3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/b7/tph8q_z12_lb13s4wd7rk1ch0000gn/T/pip-pip-egg-info-3q6va8k9
         cwd: /private/var/folders/b7/tph8q_z12_lb13s4wd7rk1ch0000gn/T/pip-install-qkkjas4s/faktory_710524b00c484ed9950199e63eee2b3d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b7/tph8q_z12_lb13s4wd7rk1ch0000gn/T/pip-install-qkkjas4s/faktory_710524b00c484ed9950199e63eee2b3d/setup.py", line 4, in <module>
        dev_requires = open("dev-requirements.txt").read().strip().split("\n")
    FileNotFoundError: [Errno 2] No such file or directory: 'dev-requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/77/4a47ad1a84d33faaf179f0eb7f2e2f9d2d94118f9517d393aaf7d710d05d/faktory-0.5.0.tar.gz#sha256=101630a5788f5d11c17a1d5f0e1e04a8cc9164a886f54846fe29317d91d51327 (from https://pypi.org/simple/faktory/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faktory==0.5.0
ERROR: No matching distribution found for faktory==0.5.0
```

**Comment by joosterman** [comment]
@cdrx Do you know how this can be resolved?

**Comment by cdrx** [comment]
Damn. Thanks for the report. I’ve yanked 0.5 from PyPi for now.

I’ll release 0.5.1 fixing this tomorrow.

**Comment by cdrx** [comment]
Sorry for the delay. This is fixed now. 0.5.1 is published on PyPi and I've checked that it can be installed successfully. 

```
❯ pip3 install faktory==0.5.1
Collecting faktory==0.5.1
  Downloading faktory-0.5.1.tar.gz (9.8 kB)
Building wheels for collected packages: faktory
  Building wheel for faktory (setup.py) ... done
  Created wheel for faktory: filename=faktory-0.5.1-py3-none-any.whl size=9977 sha256=223cbb9ac591a000ed2796aad8f38d70901954a4e4bd95e5fd13da2db73c5eef
Successfully built faktory
Installing collected packages: faktory
Successfully installed faktory-0.5.1
```
